# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
sensio_framework_extra:
    request: { converters: true }
fos_rest:
    body_converter:
        enabled: true
    view:
        formats: { json: true, xml: false, rss: false }
        view_response_listener: true
    format_listener:
        rules:
            - { path: '^/', priorities: ['json', 'yml', 'html'], fallback_format: 'json' }